version: "3"
services:
  server:
    image: api-production
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
  webportal:
    image: webportal-production
    ports:
      - "3030:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SRKADMIN
      - MONGO_INITDB_ROOT_PASSWORD=SRKSECRETPASSWORD
    volumes:
      - ./database:/data/db