version: "3"
services:
  server:
    build: ./api/
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
  webportal:
    build: ./frontend/webportal/
    ports:
      - "3030:3030"
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SRKADMIN
      - MONGO_INITDB_ROOT_PASSWORD=SRKSECRETPASSWORD
    volumes:
      - ./database:/data/db